### ISSUE TITLE
PivotLens does not work correctly when there is more than one row for a target attribute value for one key value

### ISSUE THREAD

**Issue by lordpretzel** [UBOdin/mimir-api#12]
This is seen in the test case of lenses: `key: C`, `target: A`, `value: B`.

~~~sh
[error] x Pivot A Table To Multiple Rows
[error]  (3,null,2) != (3,2,null) (PivotLensSpec.scala:61)
~~~

where the data is as shown below (note that for `C:1` there are two rows for `A:2`)

| A | B | C |
|---+---+---|
| 1 | 3 | 1 |
| 2 |   | 1 |
| 2 | 2 | 1 |
| 1 | 4 | 2 |
| 1 | 2 | 3 |
| 4 | 2 | 4 |
| 1 | 2 |   |

The lens returns a schema `C, B_1, B_2, B_4` and should returns

| C | B_1 | B_2 | B_4  |
|---|-----|-----|------|
| 1 | 3   | 2   | NULL |

but returns

| C | B_1 | B_2  | B_4 |
|---|-----|------|-----|
| 1 | 3   | NULL | 2   |

**Comment by okennedy** [comment]
This is the correct result.  The result is

| C | B_1 | B_2 | B_4 |
|---|-----|-----|-----|
| 1 | FIRST(B) WHERE A = 1 AND C = 1 | FIRST(B) WHERE A = 2 AND C = 1 | FIRST(B) WHERE A = 4 AND C = 1 |

which is...

| C | B_1 | B_2 | B_4 |
|---|-----|-----|-----|
| 1 | FIRST( { 1 } ) = 1 | FIRST( { NULL, 2 } ) = 2 | FIRST( {} ) = NULL |
